import Markdown from "@ronradtke/react-native-markdown-display"
import { StyleSheet, Text, View } from "react-native"

export type AnswerPresentationSource = { key: string; citationLabel?: string; document: string; page: number | null; excerpt: string; scores?: Record<string, number | null> }
export type AnswerPresentationModel = { answer: string; grounded: boolean; sources: AnswerPresentationSource[]; sourcesTitle: string; showCitationId: boolean }
function sourceFilename(source: string): string { return source.replaceAll("\\", "/").split("/").filter(Boolean).at(-1) ?? source }
function GroundingStatus({ grounded, hasSources }: { grounded: boolean; hasSources: boolean }) {
  if (grounded) return <View style={[styles.groundingCard, styles.groundingVerified]}><Text style={styles.groundingTitle}>Citações verificadas</Text><Text style={styles.groundingText}>As afirmações informativas estão acompanhadas de referências do corpus.</Text><Text style={styles.groundingText}>Isso representa cobertura estrutural de citações, não garantia clínica.</Text></View>
  if (hasSources) return <View style={[styles.groundingCard, styles.groundingWarning]}><Text style={styles.groundingTitle}>Citações não verificadas</Text><Text style={styles.groundingText}>Não foi possível validar as citações desta resposta. Consulte as fontes recuperadas abaixo.</Text></View>
  return <View style={[styles.groundingCard, styles.groundingWarning]}><Text style={styles.groundingTitle}>Sem base documental suficiente</Text><Text style={styles.groundingText}>Não foram encontrados trechos relevantes o bastante para fundamentar uma resposta.</Text></View>
}
export function AnswerPresentation({ model }: { model: AnswerPresentationModel }) {
  return <View style={styles.wrapper}><Markdown style={markdownStyles}>{model.answer}</Markdown><GroundingStatus grounded={model.grounded} hasSources={model.sources.length > 0} />{model.sources.length > 0 ? <View style={styles.sourcesSection}><Text style={styles.sourcesTitle}>{model.sourcesTitle}</Text><View style={styles.sourcesList}>{model.sources.map((source) => <View key={source.key} style={styles.sourceCard}><View style={styles.sourceHeader}>{model.showCitationId && source.citationLabel ? <Text style={styles.citationBadge}>{source.citationLabel}</Text> : null}<Text style={styles.sourceTitle}>{sourceFilename(source.document)}</Text></View><Text style={styles.sourceMeta}>{source.page === null ? "Página não informada" : `Página ${source.page}`}</Text>{source.excerpt ? <Text numberOfLines={3} style={styles.sourceExcerpt}>{source.excerpt}</Text> : null}{source.scores ? <View>{Object.entries(source.scores).map(([label, score]) => <Text key={label} style={styles.score}>{label}: {score === null ? "Não disponível" : score}</Text>)}</View> : null}</View>)}</View></View> : null}</View>
}
const markdownStyles = StyleSheet.create({ body: { color: "#17191C", fontSize: 16, lineHeight: 24 }, paragraph: { marginTop: 0, marginBottom: 10 }, strong: { fontWeight: "700" }, bullet_list: { marginVertical: 4 }, ordered_list: { marginVertical: 4 }, list_item: { marginVertical: 3 }, link: { textDecorationLine: "underline" } })
const styles = StyleSheet.create({ wrapper: { gap: 16 }, groundingCard: { gap: 4, borderRadius: 12, padding: 12 }, groundingVerified: { backgroundColor: "#F3F5F7" }, groundingWarning: { backgroundColor: "#FFF7E6" }, groundingTitle: { fontSize: 13, fontWeight: "700" }, groundingText: { fontSize: 13, lineHeight: 18 }, sourcesSection: { gap: 10, borderTopWidth: 1, borderTopColor: "#E1E4E8", paddingTop: 14 }, sourcesTitle: { fontSize: 14, fontWeight: "700" }, sourcesList: { gap: 10 }, sourceCard: { gap: 6, borderWidth: 1, borderColor: "#E1E4E8", borderRadius: 14, padding: 12, backgroundColor: "#FAFBFC" }, sourceHeader: { flexDirection: "row", alignItems: "flex-start", gap: 8 }, citationBadge: { fontSize: 13, fontWeight: "700" }, sourceTitle: { flex: 1, fontSize: 14, fontWeight: "600" }, sourceMeta: { fontSize: 12 }, sourceExcerpt: { fontSize: 13, lineHeight: 18 }, score: { fontSize: 12 } })
