import Markdown from "@ronradtke/react-native-markdown-display"
import { StyleSheet, Text, View } from "react-native"

export type AnswerPresentationSource = { key: string; citationLabel?: string; document: string; page: number | null; excerpt: string; scores?: Record<string, number | null> }
export type AnswerPresentationPalette = { text: string; textMuted: string; surface: string; surfaceMuted: string; border: string; accent: string }
export type AnswerPresentationModel = { answer: string; grounded: boolean; sources: AnswerPresentationSource[]; sourcesTitle: string; showCitationId: boolean; palette?: AnswerPresentationPalette }
function sourceFilename(source: string): string { return source.replaceAll("\\", "/").split("/").filter(Boolean).at(-1) ?? source }
const defaultPalette: AnswerPresentationPalette = { text: "#17191C", textMuted: "#43515D", surface: "#FAFBFC", surfaceMuted: "#F3F5F7", border: "#E1E4E8", accent: "#17191C" }
function GroundingStatus({ grounded, hasSources, palette }: { grounded: boolean; hasSources: boolean; palette: AnswerPresentationPalette }) {
  const cardStyle = [styles.groundingCard, { backgroundColor: palette.surfaceMuted, borderColor: palette.border }]
  if (grounded) return <View style={cardStyle}><Text style={[styles.groundingTitle, { color: palette.text }]}>Citações verificadas</Text><Text style={[styles.groundingText, { color: palette.text }]}>As afirmações informativas estão acompanhadas de referências do corpus.</Text><Text style={[styles.groundingText, { color: palette.textMuted }]}>Isso indica cobertura estrutural de citações; não garante verdade factual ou clínica.</Text></View>
  if (hasSources) return <View style={cardStyle}><Text style={[styles.groundingTitle, { color: palette.text }]}>Citações não verificadas</Text><Text style={[styles.groundingText, { color: palette.text }]}>Não foi possível validar as citações desta resposta. Consulte as fontes recuperadas abaixo.</Text><Text style={[styles.groundingText, { color: palette.textMuted }]}>A ausência de verificação não permite concluir verdade factual ou clínica.</Text></View>
  return <View style={cardStyle}><Text style={[styles.groundingTitle, { color: palette.text }]}>Sem base documental suficiente</Text><Text style={[styles.groundingText, { color: palette.text }]}>Não foram encontrados trechos relevantes o bastante para fundamentar uma resposta.</Text><Text style={[styles.groundingText, { color: palette.textMuted }]}>Não há cobertura estrutural suficiente para indicar verdade factual ou clínica.</Text></View>
}
export function AnswerPresentation({ model }: { model: AnswerPresentationModel }) {
  const palette = model.palette ?? defaultPalette
  return <View style={styles.wrapper}><Markdown style={markdownStyles(palette.text)}>{model.answer}</Markdown><GroundingStatus grounded={model.grounded} hasSources={model.sources.length > 0} palette={palette} />{model.sources.length > 0 ? <View style={[styles.sourcesSection, { borderTopColor: palette.border }]}><Text style={[styles.sourcesTitle, { color: palette.text }]}>{model.sourcesTitle}</Text><View style={styles.sourcesList}>{model.sources.map((source) => <View key={source.key} style={[styles.sourceCard, { backgroundColor: palette.surface, borderColor: palette.border }]}><View style={styles.sourceHeader}>{model.showCitationId && source.citationLabel ? <Text style={[styles.citationBadge, { color: palette.accent }]}>{source.citationLabel}</Text> : null}<Text numberOfLines={2} ellipsizeMode="tail" style={[styles.sourceTitle, { color: palette.text }]}>{sourceFilename(source.document)}</Text></View><Text style={[styles.sourceMeta, { color: palette.textMuted }]}>{source.page === null ? "Página não informada" : `Página ${source.page}`}</Text>{source.excerpt ? <Text numberOfLines={3} style={[styles.sourceExcerpt, { color: palette.text }]}>{source.excerpt}</Text> : null}{source.scores ? <View>{Object.entries(source.scores).map(([label, score]) => <Text key={label} style={[styles.score, { color: palette.textMuted }]}>{label}: {score === null ? "Não disponível" : score}</Text>)}</View> : null}</View>)}</View></View> : null}</View>
}
const markdownStyles = (text: string) => StyleSheet.create({ body: { color: text, fontSize: 16, lineHeight: 24 }, paragraph: { marginTop: 0, marginBottom: 10 }, strong: { fontWeight: "700" }, bullet_list: { marginVertical: 4 }, ordered_list: { marginVertical: 4 }, list_item: { marginVertical: 3 }, link: { textDecorationLine: "underline", color: text } })
const styles = StyleSheet.create({ wrapper: { gap: 16 }, groundingCard: { gap: 4, borderRadius: 12, padding: 12, borderWidth: 1 }, groundingTitle: { fontSize: 13, fontWeight: "700" }, groundingText: { fontSize: 13, lineHeight: 18 }, sourcesSection: { gap: 10, borderTopWidth: 1, paddingTop: 14 }, sourcesTitle: { fontSize: 14, fontWeight: "700" }, sourcesList: { gap: 10 }, sourceCard: { gap: 6, borderWidth: 1, borderRadius: 14, padding: 12 }, sourceHeader: { flexDirection: "row", alignItems: "flex-start", gap: 8, minWidth: 0 }, citationBadge: { fontSize: 13, fontWeight: "700" }, sourceTitle: { flex: 1, flexShrink: 1, minWidth: 0, fontSize: 14, fontWeight: "600" }, sourceMeta: { fontSize: 12 }, sourceExcerpt: { fontSize: 13, lineHeight: 18 }, score: { fontSize: 12 } })
