import { useState } from "react"
import { Pressable, StyleSheet, Text, View } from "react-native"
import { PipelineStage } from "../components/pipeline-stage"
import { useDemoTheme } from "../components/demo-shell-theme"
import { buildDemoPipeline } from "../state/demo-pipeline-model"
import type { DemoRunState } from "../types/run-state"

export const stages = [
  ["question", "Pergunta", "A pergunta orienta a futura consulta.", "No M3, o texto será validado antes de entrar no contrato de execução."], ["analysis", "Análise e decomposição", "A intenção pode ser organizada em partes verificáveis.", "A decomposição, quando aplicável, continua limitada ao contrato de consulta."], ["embedding", "Embedding", "A pergunta pode ser representada para busca semântica.", "O embedding usa o modelo configurado no pipeline, sem execução nesta tela."], ["qdrant", "Qdrant", "A coleção vetorial armazena os pontos documentais.", "A coleção e seus parâmetros permanecem somente leitura durante o M2."], ["retrieval", "Retrieval", "Documentos públicos relevantes serão recuperados.", "O modo e os filtros seguirão os schemas fechados do M1."], ["reranking", "Reranking", "Os candidatos podem ser reordenados por relevância.", "A reordenação será medida no replay futuro, sem fabricar ranking agora."], ["context", "Contexto", "Trechos selecionados formam o contexto da resposta.", "O contexto deverá respeitar limites de fonte e privacidade."], ["llm", "LLM", "Uma resposta poderá ser produzida por provider configurado.", "A geração permanece fora do M2 e exigirá revisão de privacidade."], ["citations", "Validação de citações", "As referências precisam corresponder aos trechos usados.", "A cobertura estrutural de citações não equivale a prova clínica."], ["grounding", "Grounding", "O estado indica se há base documental citável.", "Grounded é cobertura estrutural, não garantia de verdade clínica."], ["answer", "Resposta", "A resposta final apresenta a informação e suas fontes.", "A resposta só será exibida após uma execução controlada e auditável."],
] as const
const initialState: DemoRunState = { question: null, response: null, diagnostics: null, runtime: null, runtimeStatus: "idle", runtimeError: null, status: "idle", error: null }

export function HowItWorksScreen({ state: providedState, mode = "auto", presentationIndex = 0, onModeChange, onPresentationIndexChange }: { state?: DemoRunState; mode?: "auto" | "presentation"; presentationIndex?: number; onModeChange?: (mode: "auto" | "presentation") => void; onPresentationIndexChange?: (index: number) => void }) {
  const theme = useDemoTheme(); const [expanded, setExpanded] = useState<string | null>(null); const legacy = !providedState; const state = providedState ?? initialState; const pipeline = buildDemoPipeline(state); const shown = legacy ? stages.map(([id, title, simpleExplanation, technicalDetails]) => ({ id, title, simpleExplanation, technicalDetails, state: "awaiting-execution" as const })) : mode === "presentation" ? pipeline.slice(Math.max(0, Math.min(presentationIndex, pipeline.length - 1)), Math.max(0, Math.min(presentationIndex, pipeline.length - 1)) + 1) : pipeline; const current = Math.max(0, Math.min(presentationIndex, pipeline.length - 1))
  return <View style={styles.screen}><Text style={[styles.title, { color: theme.text }]}>Como funciona</Text><Text style={{ color: theme.textMuted }}>{state.response ? "Veja os dados da mesma execução apresentada no Chat." : "Execute uma pergunta no Chat para visualizar o pipeline"}</Text><View style={styles.controls}><Pressable accessibilityRole="button" accessibilityLabel="Automático" accessibilityState={{ selected: mode === "auto" }} onPress={() => onModeChange?.("auto")} style={[styles.control, { borderColor: theme.border }]}><Text style={{ color: theme.text }}>Ver tudo</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel="Apresentação" accessibilityState={{ selected: mode === "presentation" }} onPress={() => onModeChange?.("presentation")} style={[styles.control, { borderColor: theme.border }]}><Text style={{ color: theme.text }}>Apresentação</Text></Pressable></View>{mode === "presentation" ? <View style={styles.controls}><Pressable accessibilityRole="button" accessibilityLabel="Anterior" accessibilityState={{ disabled: current === 0 }} disabled={current === 0} onPress={() => onPresentationIndexChange?.(current - 1)} style={[styles.control, { borderColor: theme.border }]}><Text style={{ color: theme.text }}>Anterior</Text></Pressable><Text style={{ color: theme.textMuted }}>{current + 1} de {pipeline.length}</Text><Pressable accessibilityRole="button" accessibilityLabel="Próximo" accessibilityState={{ disabled: current === pipeline.length - 1 }} disabled={current === pipeline.length - 1} onPress={() => onPresentationIndexChange?.(current + 1)} style={[styles.control, { borderColor: theme.border }]}><Text style={{ color: theme.text }}>Próximo</Text></Pressable></View> : null}{shown.map((stage) => <PipelineStage key={stage.id} {...stage} expanded={expanded === stage.id} onToggle={() => setExpanded((value) => value === stage.id ? null : stage.id)} />)}</View>
}
const styles = StyleSheet.create({ screen: { gap: 12 }, title: { fontSize: 24, fontWeight: "800" }, controls: { flexDirection: "row", alignItems: "center", gap: 8, flexWrap: "wrap" }, control: { minHeight: 44, justifyContent: "center", paddingHorizontal: 12, borderWidth: 1, borderRadius: 8 } })
