import { useEffect, useRef, useState } from "react"
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View, useWindowDimensions } from "react-native"
import { sanitizeDemoApiError, type DemoApi } from "../api/demo-api"
import { invalidDemoResponse, validateDemoRequest } from "../api/demo-api-validation"
import { LAB_BENCHMARKS, LAB_RATIONALE, LAB_STRATEGIES, deriveComparisonMetrics, type LabExecution, type LabStrategy } from "../laboratory/laboratory-model"
import { demoExamples } from "./demo-chat-screen"
import { useDemoTheme } from "../components/demo-shell-theme"
import type { DemoApiError, DemoRetrievalResponse } from "../types/api"

type LaboratoryScreenProps = { api?: DemoApi | null; apiError?: DemoApiError | null }

function initialExecutions(): Record<LabStrategy, LabExecution> {
  return Object.fromEntries(LAB_STRATEGIES.map(({ id }) => [id, { strategy: id, status: "idle", response: null, error: null, revision: 0 }])) as Record<LabStrategy, LabExecution>
}

function validateRetrievalResponse(response: DemoRetrievalResponse, query: string, strategy: LabStrategy, limit: number): DemoRetrievalResponse {
  if (response.query !== query || response.retrieval_mode !== strategy) throw invalidDemoResponse()
  const orders = response.sources.map((source) => source.order)
  if (response.sources.length > limit || orders.some((order) => !Number.isInteger(order) || order < 1) || new Set(orders).size !== orders.length || orders.some((order, index) => order !== index + 1)) throw invalidDemoResponse()
  return response
}

function Score({ label, value, color }: { label: string; value: number | null; color: string }) { return <Text style={{ color }}>{`${label}: ${value === null ? "Não disponível" : value}`}</Text> }

function SourceResult({ source, theme }: { source: DemoRetrievalResponse["sources"][number]; theme: ReturnType<typeof useDemoTheme> }) {
  return <View style={[styles.source, { borderColor: theme.border, backgroundColor: theme.surface }]}><Text style={[styles.rank, { color: theme.action }]}>{`#${source.order}`}</Text><Text numberOfLines={2} ellipsizeMode="tail" style={[styles.document, { color: theme.text }]}>{source.document}</Text><Text style={{ color: theme.textMuted }}>{`ID público: ${source.public_id}`}</Text><Text style={{ color: theme.textMuted }}>{`Página: ${source.page === null ? "Não disponível" : source.page}`}</Text><Text style={{ color: theme.textMuted }}>{source.excerpt}</Text><View style={styles.scores}><Score label="Dense" value={source.scores.dense_score} color={theme.textMuted} /><Score label="Sparse" value={source.scores.sparse_score} color={theme.textMuted} /><Score label="Rank" value={source.scores.rank_score} color={theme.textMuted} /><Score label="Fusion" value={source.scores.fusion_score} color={theme.textMuted} /></View></View>
}

export function LaboratoryScreen({ api = null, apiError = null }: LaboratoryScreenProps) {
  const theme = useDemoTheme(); const { width } = useWindowDimensions(); const compact = width < 640
  const [query, setQuery] = useState(""); const [strategy, setStrategy] = useState<LabStrategy>("dense"); const [compareAll, setCompareAll] = useState(false); const [limit, setLimit] = useState(5); const [executions, setExecutions] = useState<Record<LabStrategy, LabExecution>>(initialExecutions); const revisionRef = useRef(0); const experimentRef = useRef<{ query: string; limit: number; revision: number } | null>(null)
  useEffect(() => { revisionRef.current += 1; experimentRef.current = null }, [api])
  const activeExecutions = LAB_STRATEGIES.map(({ id }) => executions[id]).filter((execution) => execution.status === "success" || execution.status === "error" || execution.status === "loading")
  const currentRevision = Math.max(0, ...activeExecutions.map((execution) => execution.revision))
  const visibleExecutions = activeExecutions.filter((execution) => execution.revision === currentRevision && (compareAll || execution.strategy === strategy))
  const successful = visibleExecutions.filter((execution): execution is LabExecution & { response: DemoRetrievalResponse } => execution.status === "success" && execution.response !== null)
  const metrics = successful.length > 0 ? deriveComparisonMetrics(successful.map(({ strategy: mode, response }) => ({ strategy: mode, response }))) : null
  const isLoading = Object.values(executions).some((execution) => execution.status === "loading")

  async function executeOne(mode: LabStrategy, normalizedQuery: string, selectedLimit: number, revision: number) {
    if (!api) return
    setExecutions((current) => ({ ...current, [mode]: { strategy: mode, status: "loading", response: null, error: null, revision } }))
    try {
      const request = validateDemoRequest({ query: normalizedQuery, limit: selectedLimit, retrieval_mode: mode }); const response = validateRetrievalResponse(await api.retrieve(request), normalizedQuery, mode, selectedLimit)
      if (revisionRef.current !== revision) return
      setExecutions((current) => ({ ...current, [mode]: { strategy: mode, status: "success", response, error: null, revision } }))
    } catch (error) {
      if (revisionRef.current !== revision) return
      setExecutions((current) => ({ ...current, [mode]: { strategy: mode, status: "error", response: null, error: sanitizeDemoApiError(error), revision } }))
    }
  }

  async function execute() {
    const normalizedQuery = query.trim(); if (!api || normalizedQuery.length < 2 || isLoading) return
    const revision = revisionRef.current + 1; revisionRef.current = revision; experimentRef.current = { query: normalizedQuery, limit, revision }; const modes = compareAll ? LAB_STRATEGIES.map(({ id }) => id) : [strategy]
    setExecutions((current) => Object.fromEntries(LAB_STRATEGIES.map(({ id }) => [id, modes.includes(id) || compareAll ? { strategy: id, status: "idle", response: null, error: null, revision } : current[id]])) as Record<LabStrategy, LabExecution>)
    for (const mode of modes) await executeOne(mode, normalizedQuery, limit, revision)
  }

  async function retry(mode: LabStrategy) { const experiment = experimentRef.current; if (!api || !experiment || isLoading) return; const revision = executions[mode].revision || experiment.revision; await executeOne(mode, experiment.query, experiment.limit, revision) }

  return <View style={styles.screen}><Text style={[styles.title, { color: theme.text }]}>Laboratório</Text><Text style={{ color: theme.textMuted }}>Compare o retrieval documental real. Esta superfície não gera resposta e não chama um provedor de LLM.</Text>
    <View style={[styles.panel, { borderColor: theme.border, backgroundColor: theme.surface }]}><Text style={[styles.sectionTitle, { color: theme.text }]}>Pergunta</Text><Text style={{ color: theme.textMuted }}>Use apenas perguntas públicas; não inclua nomes, prontuários ou outros dados pessoais.</Text><TextInput accessibilityLabel="Pergunta do laboratório" editable={!isLoading} multiline value={query} onChangeText={setQuery} placeholder="Escreva uma pergunta pública" placeholderTextColor={theme.textMuted} style={[styles.input, { color: theme.text, borderColor: theme.border, backgroundColor: theme.surfaceMuted }]} /><Text style={[styles.label, { color: theme.text }]}>Exemplos públicos (preenchem somente o campo)</Text><View style={styles.examples}>{demoExamples.map((example) => <Pressable key={example.caseId} accessibilityRole="button" accessibilityLabel={`Usar exemplo: ${example.query}`} accessibilityState={{ disabled: isLoading }} disabled={isLoading} onPress={() => setQuery(example.query)} style={[styles.example, { borderColor: theme.border }, isLoading && styles.disabled]}><Text style={{ color: theme.action }}>{example.query}</Text></Pressable>)}</View></View>
    <View style={[styles.panel, { borderColor: theme.border, backgroundColor: theme.surface }]}><Text style={[styles.sectionTitle, { color: theme.text }]}>Configuração da execução</Text><Text style={{ color: theme.textMuted }}>Escolha controles e execute explicitamente. Alterá-los não dispara requisições.</Text><Text style={[styles.label, { color: theme.text }]}>Estratégia</Text><View style={styles.controlRow}>{LAB_STRATEGIES.map(({ id, label }) => <Pressable key={id} accessibilityRole="button" accessibilityLabel={label} accessibilityState={{ selected: !compareAll && strategy === id }} onPress={() => { setStrategy(id); setCompareAll(false) }} style={[styles.control, { borderColor: !compareAll && strategy === id ? theme.action : theme.border, backgroundColor: !compareAll && strategy === id ? theme.surfaceMuted : theme.surface }]}><Text style={{ color: theme.text }}>{label}</Text></Pressable>)}<Pressable accessibilityRole="button" accessibilityLabel="Comparar todas" accessibilityState={{ selected: compareAll }} onPress={() => setCompareAll(true)} style={[styles.control, { borderColor: compareAll ? theme.action : theme.border, backgroundColor: compareAll ? theme.surfaceMuted : theme.surface }]}><Text style={{ color: theme.text }}>Comparar todas</Text></Pressable></View><Text style={[styles.label, { color: theme.text }]}>Perfis disponíveis</Text>{LAB_STRATEGIES.map(({ id, label, description }) => <Text key={id} style={{ color: theme.textMuted }}>{label}: {description}</Text>)}<Text style={[styles.label, { color: theme.text }]}>Top K (enviado como limit)</Text><View style={styles.controlRow}>{[3, 5, 10].map((value) => <Pressable key={value} accessibilityRole="button" accessibilityLabel={`Top K ${value}`} accessibilityState={{ selected: limit === value }} onPress={() => setLimit(value)} style={[styles.control, { borderColor: limit === value ? theme.action : theme.border, backgroundColor: limit === value ? theme.surfaceMuted : theme.surface }]}><Text style={{ color: theme.text }}>{value}</Text></Pressable>)}</View><Pressable accessibilityRole="button" accessibilityLabel={compareAll ? "Executar comparação" : "Executar retrieval"} accessibilityState={{ disabled: isLoading || !api }} disabled={isLoading || !api} onPress={() => void execute()} style={[styles.action, { backgroundColor: theme.action }, (isLoading || !api) && styles.disabled]}><Text style={{ color: theme.actionText }}>{isLoading ? "Executando..." : compareAll ? "Executar comparação" : "Executar retrieval"}</Text></Pressable>{apiError ? <Text style={{ color: theme.warning }}>{apiError.message}</Text> : null}</View>
    {visibleExecutions.length > 0 ? <><View style={[styles.warning, { borderColor: theme.warning, backgroundColor: theme.surfaceMuted }]}><Text style={[styles.sectionTitle, { color: theme.warning }]}>Comparabilidade</Text><Text style={{ color: theme.text }}>Scores não são diretamente comparáveis entre estratégias.</Text><Text style={{ color: theme.text }}>Eles descrevem sinais diferentes; esta tela não escolhe uma estratégia por score.</Text><Text style={{ color: theme.textMuted }}>Tempos dependem da máquina local, cache e carga do serviço.</Text></View><View style={[styles.results, compact ? styles.stack : styles.columns]}>{visibleExecutions.map((execution) => <View key={`${execution.strategy}-${execution.revision}`} style={compact ? styles.full : styles.resultColumn}>{renderExecution(execution, theme, retry)}</View>)}</View>{compareAll && successful.length < 3 && visibleExecutions.every((execution) => execution.status !== "loading") ? <Text style={{ color: theme.warning }}>Comparação parcial: métricas de sobreposição aguardam as três estratégias disponíveis.</Text> : null}{metrics && successful.length > 1 && (!compareAll || successful.length === 3) ? <View style={[styles.panel, { borderColor: theme.border, backgroundColor: theme.surface }]}><Text style={[styles.sectionTitle, { color: theme.text }]}>Métricas descritivas desta execução</Text><Text style={{ color: theme.textMuted }}>Sem julgamento de qualidade por score.</Text>{successful.map(({ strategy: mode }) => <Text key={mode} style={{ color: theme.text }}>{mode}: {metrics.byStrategy[mode].resultCount} resultados · {metrics.byStrategy[mode].uniqueDocuments} documentos únicos</Text>)}<Text style={{ color: theme.text }}>Todas as três: {metrics.allThree.count} fonte(s)</Text>{metrics.pairOverlap.map((item) => <Text key={`${item.left}-${item.right}`} style={{ color: theme.text }}>Sobreposição {item.left} × {item.right}: {item.count}</Text>)}{metrics.exclusive.map((item) => <Text key={item.strategy} style={{ color: theme.text }}>Exclusivas de {item.strategy}: {item.count}</Text>)}{metrics.rankDeltas.length > 0 ? <Text style={{ color: theme.text }}>Mudanças de posição: {metrics.rankDeltas.length} fonte(s) observada(s)</Text> : null}</View> : null}</> : null}
    <View style={[styles.panel, { borderColor: theme.border, backgroundColor: theme.surface }]}><Text style={[styles.sectionTitle, { color: theme.text }]}>Multi-query / decomposição</Text><Text style={{ color: theme.textMuted }}>Indisponível nesta versão: o contrato retrieval-only não expõe decomposição ou subconsultas observáveis. Nenhum campo é simulado.</Text></View>
    <View style={[styles.panel, { borderColor: theme.border, backgroundColor: theme.surface }]}><Text style={[styles.sectionTitle, { color: theme.text }]}>Resultados de avaliações anteriores</Text><Text style={{ color: theme.textMuted }}>Benchmarks históricos, não a pontuação desta execução local. Dataset congelado: 2026-09-20-v1.</Text>{(["DEV", "HOLDOUT"] as const).map((split) => <View key={split} style={styles.benchmark}><Text style={[styles.label, { color: theme.text }]}>{split} · 2026-09-20-v1</Text>{LAB_BENCHMARKS.filter((row) => row.split === split).map((row) => <Text key={row.strategy} style={{ color: theme.text }}>{row.strategy}: HitRate {row.metrics["HitRate@5"].toFixed(3)} · MRR {row.metrics["MRR@5"].toFixed(3)} · SourceRecall {row.metrics["SourceRecall@5"].toFixed(3)} · SourceNDCG {row.metrics["SourceNDCG@5"].toFixed(3)}</Text>)}</View>)}<Text style={{ color: theme.textMuted }}>HitRate: presença de uma fonte esperada no top-k; MRR: posição da primeira fonte esperada; SourceRecall: cobertura de fontes distintas; SourceNDCG: ordenação das fontes esperadas. DEV reúne consultas de desenvolvimento; HOLDOUT reúne consultas congeladas para verificação de generalização. Fonte: {LAB_BENCHMARKS[0].source}. As métricas preservam semântica histórica e não são prova clínica.</Text></View>
    <View style={[styles.panel, { borderColor: theme.border, backgroundColor: theme.surface }]}><Text style={[styles.sectionTitle, { color: theme.text }]}>{LAB_RATIONALE.title}</Text><Text style={{ color: theme.text }}>{LAB_RATIONALE.simple}</Text><Text style={{ color: theme.text }}>{LAB_RATIONALE.technical}</Text><Text style={{ color: theme.text }}>{LAB_RATIONALE.method}</Text><Text style={{ color: theme.textMuted }}>{LAB_RATIONALE.disclaimer}</Text><Text style={{ color: theme.textMuted }}>Fontes: {LAB_RATIONALE.sources}</Text></View>
  </View>
}

function renderExecution(execution: LabExecution, theme: ReturnType<typeof useDemoTheme>, retry: (mode: LabStrategy) => Promise<void>) {
  const label = LAB_STRATEGIES.find(({ id }) => id === execution.strategy)?.label ?? execution.strategy
  if (execution.status === "loading") return <View style={[styles.panel, { borderColor: theme.border, backgroundColor: theme.surface }]}><Text style={[styles.sectionTitle, { color: theme.text }]}>{label}</Text><View style={styles.loading}><ActivityIndicator /><Text style={{ color: theme.text }}>Recuperando documentos...</Text></View></View>
  if (execution.status === "error") return <View style={[styles.panel, { borderColor: theme.warning, backgroundColor: theme.surface }]}><Text style={[styles.sectionTitle, { color: theme.text }]}>{label}</Text><Text style={{ color: theme.text }}>{execution.error?.message ?? "Não foi possível concluir a busca documental."}</Text><Pressable accessibilityRole="button" accessibilityLabel={`Tentar ${label} novamente`} onPress={() => void retry(execution.strategy)} style={[styles.action, { backgroundColor: theme.action }]}><Text style={{ color: theme.actionText }}>Tentar novamente</Text></Pressable></View>
  if (execution.status !== "success" || !execution.response) return null
  const { response } = execution
  return <View style={[styles.panel, { borderColor: theme.border, backgroundColor: theme.surface }]}><Text style={[styles.sectionTitle, { color: theme.text }]}>{label}</Text><Text style={{ color: theme.textMuted }}>{`Modo retornado: ${response.retrieval_mode}`}</Text>{response.timings ? <Text style={{ color: theme.textMuted }}>{`Retrieval: ${response.timings.retrieval_ms} ms · Geração: ${response.timings.generation_ms === null ? "Não disponível" : `${response.timings.generation_ms} ms`} · Total: ${response.timings.total_ms} ms`}</Text> : <Text style={{ color: theme.textMuted }}>Tempos: Não disponível</Text>}{response.sources.map((source) => <SourceResult key={`${source.public_id}-${source.document}-${source.page ?? "null"}`} source={source} theme={theme} />)}</View>
}

const styles = StyleSheet.create({ screen: { gap: 14 }, title: { fontSize: 24, fontWeight: "800" }, sectionTitle: { fontSize: 17, fontWeight: "800" }, label: { fontSize: 13, fontWeight: "700" }, panel: { gap: 10, borderWidth: 1, borderRadius: 14, padding: 14 }, input: { minHeight: 96, borderWidth: 1, borderRadius: 10, padding: 12, fontSize: 16, textAlignVertical: "top" }, examples: { gap: 8 }, example: { minHeight: 44, justifyContent: "center", borderWidth: 1, borderRadius: 10, padding: 10 }, controlRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, control: { minHeight: 44, justifyContent: "center", borderWidth: 1, borderRadius: 10, paddingHorizontal: 12, paddingVertical: 10 }, action: { minHeight: 48, alignItems: "center", justifyContent: "center", borderRadius: 10, padding: 12 }, disabled: { opacity: 0.45 }, warning: { gap: 8, borderWidth: 1, borderRadius: 14, padding: 14 }, results: { gap: 12 }, columns: { flexDirection: "row", flexWrap: "wrap", alignItems: "flex-start" }, stack: { flexDirection: "column" }, resultColumn: { flex: 1, minWidth: 280 }, full: { width: "100%" }, source: { gap: 5, borderWidth: 1, borderRadius: 10, padding: 10 }, rank: { fontWeight: "800" }, document: { fontWeight: "700", flexShrink: 1, minWidth: 0 }, scores: { gap: 2 }, loading: { flexDirection: "row", alignItems: "center", gap: 8 }, benchmark: { gap: 4 } })
