/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness check */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_v1_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Documents */
        post: operations["search_documents_v1_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Services */
        get: operations["list_services_v1_services_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/services/{service_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Service */
        get: operations["get_service_v1_services__service_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Session */
        post: operations["create_session_v1_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_v1_sessions__session_id__get"];
        put?: never;
        post?: never;
        /** Delete Session */
        delete: operations["delete_session_v1_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Suggestions */
        get: operations["list_suggestions_v1_suggestions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChatAction */
        ChatAction: {
            /** Due Date */
            due_date?: string | null;
            /** Label */
            label: string;
            /** Note */
            note?: string | null;
            /**
             * Requires Host App
             * @default false
             */
            requires_host_app?: boolean;
            /** Service Id */
            service_id?: string | null;
            /** Suggested In Days */
            suggested_in_days?: number | null;
            /**
             * Type
             * @enum {string}
             */
            type: "open_link" | "schedule_reminder" | "call_emergency";
            /** Url */
            url?: string | null;
        };
        /** ChatDisplay */
        ChatDisplay: {
            /** Message */
            message: string;
            /**
             * Status
             * @enum {string}
             */
            status: "emergency" | "out_of_scope" | "verified" | "unverified" | "no_sources";
            /** Title */
            title: string;
            /**
             * Tone
             * @enum {string}
             */
            tone: "danger" | "neutral" | "success" | "warning";
        };
        /** ChatRequest */
        ChatRequest: {
            /** Audience */
            audience?: string | null;
            /** Auto Decompose */
            auto_decompose?: boolean | null;
            /** Category */
            category?: string | null;
            /**
             * Limit
             * @default 5
             */
            limit?: number;
            /** Message */
            message: string;
            /** Min Score */
            min_score?: number | null;
            /** Session Id */
            session_id?: string | null;
        };
        /** ChatResponse */
        ChatResponse: {
            /**
             * Actions
             * @default []
             */
            actions?: components["schemas"]["ChatAction"][];
            /** Answer */
            answer: string;
            /** Citation Ids */
            citation_ids: number[];
            /** Citation Retry Count */
            citation_retry_count: number;
            /** Decomposition Status */
            decomposition_status: string;
            display?: components["schemas"]["ChatDisplay"] | null;
            /** Grounded */
            grounded: boolean;
            /** Model */
            model: string;
            /** Multi Query Used */
            multi_query_used: boolean;
            /** Retrieval Queries */
            retrieval_queries: string[];
            /**
             * @default {
             *       "out_of_scope": false,
             *       "triaged": false
             *     }
             */
            safety?: components["schemas"]["ChatSafety"];
            /** Session Id */
            session_id?: string | null;
            /** Sources */
            sources: components["schemas"]["ChatSource"][];
        };
        /** ChatSafety */
        ChatSafety: {
            /**
             * Out Of Scope
             * @default false
             */
            out_of_scope?: boolean;
            /** Rule Id */
            rule_id?: string | null;
            /**
             * Triaged
             * @default false
             */
            triaged?: boolean;
        };
        /** ChatSource */
        ChatSource: {
            /** Audience */
            audience?: string | null;
            /** Category */
            category?: string | null;
            /**
             * Chunk Count
             * @default 1
             */
            chunk_count?: number;
            /** Citation Id */
            citation_id: number;
            /** Excerpt */
            excerpt: string;
            /** Location Label */
            location_label?: string | null;
            /** Page */
            page?: number | null;
            /** Score */
            score: number;
            /** Source */
            source: string;
            /** Title */
            title?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Environment */
            environment: string;
            /** Service */
            service: string;
            /**
             * Status
             * @default ok
             * @constant
             */
            status?: "ok";
            /** Version */
            version: string;
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            /** Dependencies */
            dependencies: {
                [key: string]: string;
            };
            /**
             * Status
             * @default ready
             * @constant
             */
            status?: "ready";
        };
        /** SemanticSearchHit */
        SemanticSearchHit: {
            /** Audience */
            audience?: string | null;
            /** Category */
            category?: string | null;
            /**
             * Chunk Count
             * @default 1
             */
            chunk_count?: number;
            /** Content */
            content: string;
            /** Dense Score */
            dense_score?: number | null;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Page */
            page?: number | null;
            /** Rank Score */
            rank_score?: number | null;
            /** Score */
            score: number;
            /** Source */
            source: string;
            /** Sparse Score */
            sparse_score?: number | null;
        };
        /** SemanticSearchRequest */
        SemanticSearchRequest: {
            /** Audience */
            audience?: string | null;
            /** Category */
            category?: string | null;
            /**
             * Limit
             * @default 5
             */
            limit?: number;
            /** Min Score */
            min_score?: number | null;
            /** Query */
            query: string;
        };
        /** SemanticSearchResponse */
        SemanticSearchResponse: {
            /** Query */
            query: string;
            /** Results */
            results: components["schemas"]["SemanticSearchHit"][];
        };
        /** ServiceDetail */
        ServiceDetail: {
            /** Alarm Signs */
            alarm_signs: string[];
            /** Audience */
            audience: string;
            /** Documents */
            documents: string[];
            /** Emergency Phone */
            emergency_phone?: string | null;
            /** Frequency */
            frequency?: string | null;
            /** How To Schedule */
            how_to_schedule: string;
            /** Id */
            id: string;
            link?: components["schemas"]["ServiceLinkOut"] | null;
            /** Name */
            name: string;
            /** Notes */
            notes: string[];
            /** Preparation */
            preparation: string[];
            /** Reminders */
            reminders: components["schemas"]["ServiceReminderOut"][];
            /** Sources */
            sources: components["schemas"]["ServiceSourceOut"][];
            /** Synonyms */
            synonyms: string[];
            /** Where */
            where: string;
            /** Who */
            who: string;
        };
        /** ServiceLinkOut */
        ServiceLinkOut: {
            /** Label */
            label: string;
            /** Url */
            url: string;
        };
        /** ServiceReminderOut */
        ServiceReminderOut: {
            /** Days */
            days: number;
            /** Label */
            label: string;
        };
        /** ServiceSourceOut */
        ServiceSourceOut: {
            /** Publisher */
            publisher: string;
            /** Title */
            title: string;
            /** Url */
            url?: string | null;
            /** Year */
            year: number;
        };
        /** ServiceSummary */
        ServiceSummary: {
            /** Audience */
            audience: string;
            /** Id */
            id: string;
            link?: components["schemas"]["ServiceLinkOut"] | null;
            /** Name */
            name: string;
        };
        /** ServicesResponse */
        ServicesResponse: {
            /** Catalog Version */
            catalog_version: string;
            /** Notice */
            notice?: string | null;
            /** Reviewed At */
            reviewed_at: string;
            /** Services */
            services: components["schemas"]["ServiceSummary"][];
        };
        /** SessionResponse */
        SessionResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * Status
             * @default active
             * @constant
             */
            status?: "active";
            /** Turns */
            turns: components["schemas"]["SessionTurnResponse"][];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SessionTurnResponse */
        SessionTurnResponse: {
            /** Answer */
            answer: string;
            /** Citation Ids */
            citation_ids: number[];
            /** Citation Retry Count */
            citation_retry_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Decomposition Status */
            decomposition_status: string;
            /** Grounded */
            grounded: boolean;
            /** Model */
            model: string;
            /** Multi Query Used */
            multi_query_used: boolean;
            /** Question */
            question: string;
            /** Retrieval Queries */
            retrieval_queries: string[];
            /** Sequence */
            sequence: number;
            /** Sources */
            sources: components["schemas"]["ChatSource"][];
            /**
             * Turn Id
             * Format: uuid
             */
            turn_id: string;
        };
        /** SuggestionItem */
        SuggestionItem: {
            /** Text */
            text: string;
            /** Topic */
            topic?: string | null;
        };
        /** SuggestionsResponse */
        SuggestionsResponse: {
            /** Suggestions */
            suggestions: components["schemas"]["SuggestionItem"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    chat_v1_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_documents_v1_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SemanticSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["SemanticSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_services_v1_services_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["ServicesResponse"];
                };
            };
        };
    };
    get_service_v1_services__service_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["ServiceDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_v1_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    get_session_v1_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_v1_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_suggestions_v1_suggestions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["SuggestionsResponse"];
                };
            };
        };
    };
}
